"""Response synthesis agent: compiles final structured clinical response."""

import json

from openai import OpenAI

from src.agents.state import AgentState

RESPONSE_PROMPT = """You are a clinical communication specialist. Compile a final, structured clinical decision support response.

Requirements:
- Every clinical claim must have a citation from the provided sources
- Use [Source N] notation to reference guideline sections
- Structure must follow the exact template below
- Flag emergencies prominently at the top if applicable
- Maintain professional clinical tone
- Include all relevant disclaimers

OUTPUT TEMPLATE:

## ⚠️ EMERGENCY ALERT (if applicable)
[Only include if emergency criteria met]

## Clinical Assessment
[Concise summary of the clinical situation]

## Differential Diagnoses
1. **[Diagnosis]** — Likelihood: [High/Medium/Low]
   - Reasoning: [Evidence-based reasoning with citations]
   - Supporting features: [Key findings]

## Recommended Investigations
- [Investigation] — [Rationale with citation]

## Management Considerations
### Immediate Actions
- [Action] [Citation]

### Pharmacological Treatment
- [Drug/dose] — [Indication] [Citation]

### Monitoring & Follow-up
- [Recommendation] [Citation]

## Sources Cited
- [Source 1]: [Full source name and document ID]

## Clinical Disclaimer
This output is generated by an AI clinical decision support tool for use by qualified healthcare professionals only. It does not constitute medical advice and must be interpreted in conjunction with clinical judgement, local protocols, and current literature. Always verify dosing with local formularies."""


class ResponseAgent:
    """Synthesizes all agent outputs into a final clinical response."""

    def __init__(self, api_key: str, model: str = "gpt-4o"):
        self._client = OpenAI(api_key=api_key)
        self.model = model

    def run(self, state: AgentState) -> AgentState:
        """Compile final response from triage, evidence, and reasoning outputs."""
        state["current_agent"] = "response"

        raw_results = state.get("raw_results", [])
        sources = list({f"{r['source']} ({r['document_id']})" for r in raw_results})
        state["sources"] = sources

        context = {
            "query": state.get("query", ""),
            "urgency": state.get("urgency", "routine"),
            "patient_info": state.get("patient_info", {}),
            "retrieved_evidence": state.get("retrieved_evidence", ""),
            "reasoning": state.get("reasoning", ""),
            "diagnoses": state.get("diagnoses", []),
            "sources": sources,
        }

        user_content = (
            f"Urgency Level: {context['urgency'].upper()}\n\n"
            f"Clinical Query: {context['query']}\n\n"
            f"Patient Information:\n{json.dumps(context['patient_info'], indent=2)}\n\n"
            f"Clinical Reasoning:\n{context['reasoning']}\n\n"
            f"Differential Diagnoses:\n{json.dumps(context['diagnoses'], indent=2)}\n\n"
            f"Retrieved Guideline Evidence:\n{context['retrieved_evidence']}\n\n"
            f"Available Sources: {', '.join(sources)}"
        )

        try:
            response = self._client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": RESPONSE_PROMPT},
                    {"role": "user", "content": user_content},
                ],
                temperature=0.2,
            )
            state["response"] = response.choices[0].message.content or ""
        except Exception as exc:
            state["response"] = f"Response generation failed: {exc}"
            state["error"] = str(exc)

        return state
